spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8091
logging:
  level:
    org:
      hibernate:
        SQL: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/         

        
